default:
  storage:
    size: 2Gi
    class: ""
  resources:
    limits:
      memory: 2048Mi
      cpu: 2000m
    requests:
      memory: 768Mi
      cpu: 100m
  image:
    name: docker.io/blacklabelops/jira
    variant: ""
    language: ""
    tag: ""
    pullPolicy: Always
  ingress:
    enabled: true
    hostname: jira.example.com
    startup: passthrough
    annotations: {}
  database:
    type: postgres
    password: changeme
  crowd:
  # enabled: true
  # application: foo
  # password: bar
  # url: https://crowd.example.com:8095/crowd
    validationinterval: 0
  sso:
    authenticator: midan
