{{- $app := printf "%s-jira" .Values.resource.name -}}
{{- $spec := dict }}
{{- $_ := merge $spec .Values.resource.spec .Values.default -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ $app }}
  labels:
    app: {{ $app }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.resource.spec.size }}
  template:
    metadata:
      labels:
        app: {{ .Values.resource.name }}
        resource: {{ $app }}
    spec:
{{- if $spec.nodeSelector }}
      nodeSelector:
{{ toYaml $spec.nodeSelector | indent 8 }}
{{ end -}}
{{- if $spec.tolerations }}
      tolerations:
{{ toYaml $spec.tolerations | indent 8 }}
{{ end }}
      containers:
        - name: jira
{{- with $spec.image }}
          image: {{ .name }}:{{ if .variant }}{{ .variant }}{{ end }}{{ if .tag }}.{{ .tag }}{{ end }}{{ if eq ( printf "%s%s" .variant .tag ) "" }}latest{{ end }}{{ if .language }}.{{ .language }}{{ end }}
          imagePullPolicy: {{ .pullPolicy }}{{ end }}
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - mountPath: /var/atlassian/jira
              name: jira-home
          envFrom:
            - secretRef:
                name: {{ $app }}-database-credentials
            - configMapRef:
                name: {{ $app }}
          volumeMounts:
            - name: jira-home
              mountPath: /var/atlassian/jira
            - name: docker-entrypoint
              mountPath: /usr/local/share/atlassian/docker-entrypoint.sh
              subPath: docker-entrypoint.sh
            {{ if $spec.crowd.enabled }}
            - name: crowd-properties
              mountPath: /usr/local/share/atlassian/crowd.properties
              subPath: crowd.properties
            {{ end }}
          resources:
{{ toYaml $spec.resources | indent 12 }}
      volumes:
        - name: jira-home
          persistentVolumeClaim:
            claimName: {{ $app }}
        - name: docker-entrypoint
          secret:
            secretName: {{ $app }}
            items:
              - key: docker-entrypoint.sh
                path: docker-entrypoint.sh
            defaultMode: 493
{{ if $spec.crowd.enabled }}
        - name: crowd-properties
          secret:
            secretName: {{ $app }}
            items:
              - key: crowd.properties
                path: crowd.properties
            defaultMode: 420
{{ end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
