{{- $app := printf "%s-jira" .Values.resource.name -}}
{{- $spec := dict }}
{{- $_ := merge $spec .Values.resource.spec .Values.default -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $app }}
  labels:
    app: {{ $app }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
{{ if $spec.crowd.enabled }}
  crowd.properties: {{ printf "application.name=%s\napplication.password=%s\ncrowd.base.url=%s\nsession.validationinterval=%.0f\n" $spec.crowd.application $spec.crowd.password $spec.crowd.url $spec.crowd.validationinterval | b64enc | quote }}
{{ end }}
  docker-entrypoint.sh: {{ .Files.Get "files/scripts/docker-entrypoint.sh" | b64enc | quote }}
